# File: .github/workflows/terraform.yml
name: Terraform CI/CD

on:
  workflow_dispatch:        # Allows manual trigger from any branch
  push:
    branches:
      - 'dev-*'            # Trigger on branches created by your POC

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # or your preferred version

      - name: Select intent folder
        id: intent
        run: |
          # Detect which folder has main.tf
          for folder in networking compute database storage security monitoring; do
            if [ -f "$folder/main.tf" ]; then
              echo "folder=$folder" >> $GITHUB_OUTPUT
              break
            fi
          done

      - name: Terraform Init
        working-directory: ${{ steps.intent.outputs.folder }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ steps.intent.outputs.folder }}
        run: terraform apply -auto-approve -input=false
