name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev-*'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Detect intent folder
        id: intent
        run: |
          for folder in networking compute database storage security monitoring; do
            if [ -f "${folder}/main.tf" ]; then
              echo "folder=${folder}" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "folder=" >> $GITHUB_OUTPUT

      - name: Terraform Init
        if: steps.intent.outputs.folder != ''
        working-directory: ${{ steps.intent.outputs.folder }}
        run: terraform init -input=false

      - name: Terraform Apply
        if: steps.intent.outputs.folder != ''
        working-directory: ${{ steps.intent.outputs.folder }}
        run: terraform apply -auto-approve -input=false
